/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.github.midnightapps.mpeapp.Application;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Application app = new Application();
        assertNotNull(app);
    }
}
